services:
  mysql:
    image: mysql:latest
    container_name: my_mysql
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_ROOT_PASSWORD=123 
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
    driver: local